### PR TITLE
Link up Configs

### PR DESCRIPTION
**Pull request by sbtoonz**
Link up the configs to all the SE stats

### CODE REVIEW

**Comment by Digitalroot** [comment]
Did you mean to edit the translation file?

**Comment by sbtoonz** [comment]
No I don't know why that got altered and can be remitted

**Comment by Digitalroot** [comment]
Okay.

**Comment by Digitalroot** [comment]
See https://github.com/GraveofBears/PotionsPlus/pull/14. Once Gravebear merges, PR into this repo from his. That should auto close this PR.

**Pull request closed without merging**
